### ISSUE TITLE
configuration not working on jira my 5.2

### ISSUE THREAD

**Issue by pablonieto** [AndreyVMarkelov/mailru-jira-plugins-issue-query-cfs#9]
Hi,

The first strange thing that happens is when I access the plugins dropdown the configuration link is placed under Others.

Once in the "Configure Query Issue Custom Fields" I find no buttons to edit the JQL clauses for the different custom fields

![image](https://f.cloud.github.com/assets/4253450/424255/2ae41900-ad82-11e2-8536-033c7cb212ae.png)

**Comment by AndreyVMarkelov** [comment]
Ah, you need to create custom fields before. Please, try on it.

**Comment by pablonieto** [comment]
I can't believe that was all! This works perfectly... my brain must have been sleeping, I thought I already had set up the custom field.

Thanks, great plugin!

**Comment by nShomik** [comment]
Hi,
I am posting here because the topic seems relevant, although I think our problem is of a different sort. When we log on as admins and go to "Administration -> Add-ons", we don't find the item "Configure Query Issue Custom Fields" under "OTHER" section in left menu column. 

We can only access this menu by typing the directory path "jira/secure/QueryConfigCfsConfig.jspa" manually after the URL. But this menu is normally not present in the menu column.

![jira-customfield-adminunavailable](https://cloud.githubusercontent.com/assets/8333672/3802180/fd239870-1c0b-11e4-85b3-3b3e330d19e6.png)

**Comment by nShomik** [comment]
Hi! we just upgraded JIRA and apparently that fixed it. Now we have this item in menu! I guess someone else noticed it too. Thanks anyway!

Cheers!
Arafat
